[package]
name = "linux_service_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
chrono = "0.4.38"
tempfile = "3.13.0"
assert_cmd = "2.0"
